### PR TITLE
Add Wireframe Lo-Fi

### LINKED ISSUE #1: [0.0.1-alpha] Missing Wireframing Lo-Fi
- [x] I am not here to ask for information or support.
- [x] I have searched in the issue track but found nothing.

### PR DESCRIPTION
**Pull request by samanthabaita**
- [x] I am not here to ask for information or support.
- [x] I have searched in the issue track but found nothing.

## Issue

Closes #1 

## Benefits

The wireframe Lo-Fi allows developers to understand the layout of Alianco.

## Context

With this wireframe Lo-Fi developers can understand the layout and starting to develop Universo accordingly.

### CODE REVIEW

**Comment by davidegiovanni** [comment]
I'd say that the wireframe is clear and follows the specs accordingly.

**Comment by lucyskyy** [comment]
I can't understand the layout of the grid. Is it responsive? The items have fixed width? How many objects can I put on in a row?
@revas/designers

**Comment by samanthabaita** [comment]
@lucyskyy Yes It is responsive, in a mobile version the card are one after the other. 
Now that we have few application we can have 4/5 cards per row.

**Comment by hashbardd** [comment]
@samanthabaita Please ignore the DS_Store files and update the specs document with the wireframe approach 😄

**Pull request merged**
